# Generated by Django 3.2 on 2022-08-24 21:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0002_auto_20220824_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'billing"."user',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_pay', models.BooleanField(verbose_name='auto_pay')),
                ('subscription_valid_to', models.DateTimeField(verbose_name='valid_to')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('last_card_digits', models.IntegerField(verbose_name='last_card_digits')),
                ('auto_pay_id', models.TextField(default=None, null=True, verbose_name='auto_pay_id')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.subscription', verbose_name='subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.user', verbose_name='user')),
            ],
            options={
                'verbose_name': 'user subscription',
                'verbose_name_plural': 'user subscriptions',
                'db_table': 'billing"."user_subscription',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.ManyToManyField(through='billing.UserSubscription', to='movies.Subscription'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.TextField(choices=[('failed', 'failed'), ('pending', 'pending'), ('succeed', 'succeed')], verbose_name='status')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.subscription', verbose_name='subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.user', verbose_name='user')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'db_table': 'billing"."transaction',
            },
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'subscription'], name='user_subsription_idx'),
        ),
    ]
