# Generated by Django 3.2 on 2022-08-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='auto_pay',
            field=models.BooleanField(default=False, verbose_name='auto_pay'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='auto_pay_id',
            field=models.TextField(null=True, verbose_name='auto_pay_id'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='last_card_digits',
            field=models.IntegerField(null=True, verbose_name='last_card_digits'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_valid_to',
            field=models.DateTimeField(null=True, verbose_name='valid_to'),
        ),
    ]
