# Generated by Django 3.2 on 2022-08-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20220824_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='active',
        ),
    ]
