# Generated by Django 3.2 on 2022-08-24 21:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('price', models.IntegerField(verbose_name='price')),
                ('period_days', models.IntegerField(verbose_name='period')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'db_table': 'content"."subscription',
            },
        ),
        migrations.AlterModelOptions(
            name='genrefilmwork',
            options={'verbose_name': 'genre', 'verbose_name_plural': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='personfilmwork',
            options={'verbose_name': 'person', 'verbose_name_plural': 'persons'},
        ),
        migrations.AddField(
            model_name='filmwork',
            name='persons',
            field=models.ManyToManyField(through='movies.PersonFilmwork', to='movies.Person'),
        ),
        migrations.AlterField(
            model_name='genrefilmwork',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre', verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.person', verbose_name='person'),
        ),
        migrations.CreateModel(
            name='SubscriptionFilmwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('film_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.filmwork')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.subscription', verbose_name='subscription')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'db_table': 'content"."subscription_film_work',
            },
        ),
        migrations.AddField(
            model_name='filmwork',
            name='subscriptions',
            field=models.ManyToManyField(through='movies.SubscriptionFilmwork', to='movies.Subscription'),
        ),
        migrations.AddIndex(
            model_name='subscriptionfilmwork',
            index=models.Index(fields=['film_work', 'subscription'], name='film_work_subsription_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionfilmwork',
            constraint=models.UniqueConstraint(fields=('film_work', 'subscription'), name='film_work_subscription_idx'),
        ),
    ]
